export const GAME_KEYWORDS = [
  { category: '과일', keyword: '사과' },
  { category: '과일', keyword: '바나나' },
  { category: '과일', keyword: '딸기' },
  { category: '과일', keyword: '수박' },
  { category: '과일', keyword: '포도' },
  { category: '과일', keyword: '복숭아' },
  { category: '과일', keyword: '망고' },
  { category: '과일', keyword: '귤' },
  { category: '과일', keyword: '파인애플' },
  { category: '과일', keyword: '체리' },
  { category: '채소', keyword: '감자' },
  { category: '채소', keyword: '당근' },
  { category: '채소', keyword: '양파' },
  { category: '채소', keyword: '브로콜리' },
  { category: '채소', keyword: '토마토' },
  { category: '채소', keyword: '오이' },
  { category: '채소', keyword: '호박' },
  { category: '채소', keyword: '옥수수' },
  { category: '채소', keyword: '버섯' },
  { category: '채소', keyword: '고추' },
  { category: '한식', keyword: '비빔밥' },
  { category: '한식', keyword: '김치찌개' },
  { category: '한식', keyword: '불고기' },
  { category: '한식', keyword: '삼겹살' },
  { category: '한식', keyword: '냉면' },
  { category: '한식', keyword: '떡볶이' },
  { category: '한식', keyword: '김밥' },
  { category: '한식', keyword: '갈비찜' },
  { category: '한식', keyword: '된장찌개' },
  { category: '한식', keyword: '잡채' },
  { category: '세계 음식', keyword: '피자' },
  { category: '세계 음식', keyword: '햄버거' },
  { category: '세계 음식', keyword: '초밥' },
  { category: '세계 음식', keyword: '파스타' },
  { category: '세계 음식', keyword: '타코' },
  { category: '세계 음식', keyword: '카레' },
  { category: '세계 음식', keyword: '쌀국수' },
  { category: '세계 음식', keyword: '라자냐' },
  { category: '세계 음식', keyword: '샌드위치' },
  { category: '세계 음식', keyword: '마라탕' },
  { category: '동물', keyword: '고양이' },
  { category: '동물', keyword: '강아지' },
  { category: '동물', keyword: '토끼' },
  { category: '동물', keyword: '코끼리' },
  { category: '동물', keyword: '기린' },
  { category: '동물', keyword: '판다' },
  { category: '동물', keyword: '펭귄' },
  { category: '동물', keyword: '사자' },
  { category: '동물', keyword: '수달' },
  { category: '동물', keyword: '카피바라' },
  { category: '바다 동물', keyword: '고래' },
  { category: '바다 동물', keyword: '상어' },
  { category: '바다 동물', keyword: '돌고래' },
  { category: '바다 동물', keyword: '문어' },
  { category: '바다 동물', keyword: '해파리' },
  { category: '바다 동물', keyword: '거북이' },
  { category: '바다 동물', keyword: '불가사리' },
  { category: '바다 동물', keyword: '가오리' },
  { category: '바다 동물', keyword: '해마' },
  { category: '바다 동물', keyword: '게' },
  { category: '곤충', keyword: '나비' },
  { category: '곤충', keyword: '무당벌레' },
  { category: '곤충', keyword: '잠자리' },
  { category: '곤충', keyword: '사마귀' },
  { category: '곤충', keyword: '개미' },
  { category: '곤충', keyword: '벌' },
  { category: '곤충', keyword: '메뚜기' },
  { category: '곤충', keyword: '반딧불이' },
  { category: '곤충', keyword: '매미' },
  { category: '곤충', keyword: '딱정벌레' },
  { category: '탈것', keyword: '자동차' },
  { category: '탈것', keyword: '버스' },
  { category: '탈것', keyword: '지하철' },
  { category: '탈것', keyword: '자전거' },
  { category: '탈것', keyword: '오토바이' },
  { category: '탈것', keyword: '기차' },
  { category: '탈것', keyword: '비행기' },
  { category: '탈것', keyword: '배' },
  { category: '탈것', keyword: '헬리콥터' },
  { category: '탈것', keyword: '열기구' },
  { category: '집 안 물건', keyword: '냉장고' },
  { category: '집 안 물건', keyword: '소파' },
  { category: '집 안 물건', keyword: '침대' },
  { category: '집 안 물건', keyword: '리모컨' },
  { category: '집 안 물건', keyword: '청소기' },
  { category: '집 안 물건', keyword: '전자레인지' },
  { category: '집 안 물건', keyword: '세탁기' },
  { category: '집 안 물건', keyword: '식탁' },
  { category: '집 안 물건', keyword: '시계' },
  { category: '집 안 물건', keyword: '거울' },
  { category: '학교 물건', keyword: '책상' },
  { category: '학교 물건', keyword: '칠판' },
  { category: '학교 물건', keyword: '연필' },
  { category: '학교 물건', keyword: '지우개' },
  { category: '학교 물건', keyword: '공책' },
  { category: '학교 물건', keyword: '가위' },
  { category: '학교 물건', keyword: '풀' },
  { category: '학교 물건', keyword: '자' },
  { category: '학교 물건', keyword: '사물함' },
  { category: '학교 물건', keyword: '급식판' },
  { category: '운동', keyword: '축구' },
  { category: '운동', keyword: '야구' },
  { category: '운동', keyword: '농구' },
  { category: '운동', keyword: '배드민턴' },
  { category: '운동', keyword: '수영' },
  { category: '운동', keyword: '탁구' },
  { category: '운동', keyword: '테니스' },
  { category: '운동', keyword: '볼링' },
  { category: '운동', keyword: '골프' },
  { category: '운동', keyword: '스케이트보드' },
  { category: '직업', keyword: '의사' },
  { category: '직업', keyword: '요리사' },
  { category: '직업', keyword: '소방관' },
  { category: '직업', keyword: '경찰관' },
  { category: '직업', keyword: '교사' },
  { category: '직업', keyword: '사진작가' },
  { category: '직업', keyword: '가수' },
  { category: '직업', keyword: '배우' },
  { category: '직업', keyword: '과학자' },
  { category: '직업', keyword: '조종사' },
  { category: '여행지', keyword: '제주도' },
  { category: '여행지', keyword: '서울' },
  { category: '여행지', keyword: '부산' },
  { category: '여행지', keyword: '파리' },
  { category: '여행지', keyword: '뉴욕' },
  { category: '여행지', keyword: '도쿄' },
  { category: '여행지', keyword: '교토' },
  { category: '여행지', keyword: '런던' },
  { category: '여행지', keyword: '하와이' },
  { category: '여행지', keyword: '이집트' },
  { category: '날씨', keyword: '비' },
  { category: '날씨', keyword: '눈' },
  { category: '날씨', keyword: '번개' },
  { category: '날씨', keyword: '무지개' },
  { category: '날씨', keyword: '태풍' },
  { category: '날씨', keyword: '안개' },
  { category: '날씨', keyword: '우박' },
  { category: '날씨', keyword: '바람' },
  { category: '날씨', keyword: '구름' },
  { category: '날씨', keyword: '서리' },
  { category: '악기', keyword: '피아노' },
  { category: '악기', keyword: '기타' },
  { category: '악기', keyword: '드럼' },
  { category: '악기', keyword: '바이올린' },
  { category: '악기', keyword: '플루트' },
  { category: '악기', keyword: '트럼펫' },
  { category: '악기', keyword: '하모니카' },
  { category: '악기', keyword: '첼로' },
  { category: '악기', keyword: '탬버린' },
  { category: '악기', keyword: '실로폰' },
  { category: '패션', keyword: '모자' },
  { category: '패션', keyword: '안경' },
  { category: '패션', keyword: '운동화' },
  { category: '패션', keyword: '목도리' },
  { category: '패션', keyword: '장갑' },
  { category: '패션', keyword: '양말' },
  { category: '패션', keyword: '넥타이' },
  { category: '패션', keyword: '우산' },
  { category: '패션', keyword: '가방' },
  { category: '패션', keyword: '팔찌' },
  { category: '놀이공원', keyword: '회전목마' },
  { category: '놀이공원', keyword: '롤러코스터' },
  { category: '놀이공원', keyword: '관람차' },
  { category: '놀이공원', keyword: '범퍼카' },
  { category: '놀이공원', keyword: '바이킹' },
  { category: '놀이공원', keyword: '자이로드롭' },
  { category: '놀이공원', keyword: '풍선' },
  { category: '놀이공원', keyword: '솜사탕' },
  { category: '놀이공원', keyword: '입장권' },
  { category: '놀이공원', keyword: '퍼레이드' },
  { category: '캐릭터', keyword: '미키마우스' },
  { category: '캐릭터', keyword: '피카츄' },
  { category: '캐릭터', keyword: '짱구' },
  { category: '캐릭터', keyword: '도라에몽' },
  { category: '캐릭터', keyword: '스폰지밥' },
  { category: '캐릭터', keyword: '헬로키티' },
  { category: '캐릭터', keyword: '미니언즈' },
  { category: '캐릭터', keyword: '슈퍼마리오' },
  { category: '캐릭터', keyword: '뽀로로' },
  { category: '캐릭터', keyword: '올라프' },
  { category: '간식', keyword: '초콜릿' },
  { category: '간식', keyword: '팝콘' },
  { category: '간식', keyword: '아이스크림' },
  { category: '간식', keyword: '쿠키' },
  { category: '간식', keyword: '도넛' },
  { category: '간식', keyword: '젤리' },
  { category: '간식', keyword: '붕어빵' },
  { category: '간식', keyword: '와플' },
  { category: '간식', keyword: '케이크' },
  { category: '간식', keyword: '마카롱' },
  { category: '꽃', keyword: '장미' },
  { category: '꽃', keyword: '튤립' },
  { category: '꽃', keyword: '해바라기' },
  { category: '꽃', keyword: '벚꽃' },
  { category: '꽃', keyword: '국화' },
  { category: '꽃', keyword: '백합' },
  { category: '꽃', keyword: '수국' },
  { category: '꽃', keyword: '민들레' },
  { category: '꽃', keyword: '라벤더' },
  { category: '꽃', keyword: '코스모스' },
] as const;
